In [1]:
from docx import Document

In [2]:
sample_file_path = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition.docx'
sample_docx= Document(sample_file_path)

In [3]:
def test():
    lines = []
    for para in sample_docx.paragraphs:
        if para.contains_page_break:
            break
        # print(para.text)
        if para.text == '':
            for run in para.runs:
                print("r",run)
                for item in run.iter_inner_content():
                    print(item)
        lines.append(para.text)
    a=0
    b=0
    for i in range(len(lines)):
        if 'כ"י של עדיות' in lines[i]:
            print(i,'כ"י של עדיות')
            a=i
        if 'מקבילות' in lines[i]:
            print(i,'מקבילות')
            b=i
        # check for section break 
    
    
    last = (b-a)-1
    print(lines[:a])
    print(b-a,(len(lines)-a)/2) 
    print(lines[a],lines[b])
    print(lines[a+1],lines[b+1])
    print(lines[a+last],lines[b+last])
test()

4 כ"י של עדיות
18 מקבילות
["מסכזתהז עזדיזותז פר' א'", "\tהרבה  וחכמ' אומ' לא כדברי זה ולא כדברי \tזה    אלא    מעת     לעת    ממעטת    על    יד 1\tמפקידה \t לפקידה     ומפקידה      לפקידה ", '', '']
14 16.5
	כ"י של עדיות מקבילות
29	הרבה | מ הרב'. מ הרב'.
	לפקידה | ר לפקיד' מ לפקי'. מ ומפקי' ד ומפקיד'.

In [132]:
def process_document(file_path,verbose=True):
    doc = Document(file_path)
    pges = []
    lines = []
    for para in doc.paragraphs:
        if para.contains_page_break:
            body = []
            cola = []
            colb = []
            a=0
            b=0
            for i in range(len(lines)):
                if 'כ"י של עדיות' in lines[i].text or 'כת"י של עדיות' in lines[i].text:
                    a=i
                if 'מקבילות' in lines[i].text:
                    b=i
                    num_lines = (b-a)
                    body = lines[:a]
                    cola= lines[a:b]
                    colb= lines[b:b+num_lines+1]
                    parallels = lines[b+num_lines+1:]
                    if  parallels and parallels[0] != '':
                        jump = 0
                        for k in range(len(parallels)):
                            if parallels[k].text == '':
                                jump = k
                                break
                        print("Uneven lines",len(pges),"jump",jump)
                        for j in range(jump):
                            colb.append(parallels[j])
                        parallels = parallels[jump:]
                    if verbose:
                        print(len(body),len(cola),len(colb),len(parallels))
                    pges.append([body,cola,colb,parallels])
            lines = [para]
        else:
            lines.append(para)
    return pges

In [80]:
pages_sample = process_document(sample_file_path)

Uneven lines 0 jump 0
4 14 15 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2

In [83]:
def create_output_document(pges):
    output_doc = Document()
    
    for page_num, page in enumerate(pges, 1):
        output_doc.add_heading(f'Page {page_num}', level=1)
        
        # Add body text
        if page[0]:
            output_doc.add_paragraph("Body Text:")
            for para in page[0]:
                output_doc.add_paragraph(para.text)
        
        # Create table for columns
        if page[1] and page[2]:
            output_doc.add_paragraph("Columns:")
            table = output_doc.add_table(rows=len(page[1]), cols=2)
            table.style = 'Table Grid'
            for i, (cola_para, colb_para) in enumerate(zip(page[1], page[2])):
                table.cell(i, 0).text = cola_para.text
                table.cell(i, 1).text = colb_para.text
        
        # Add parallels
        if page[3]:
            output_doc.add_paragraph("Parallels:")
            for para in page[3]:
                output_doc.add_paragraph(para.text)
        
        # Add page break
        output_doc.add_page_break()
    
    return output_doc

In [84]:
sample_table = create_output_document(pages_sample)
sample_table.save('/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition Output.docx')

In [102]:
from copy import deepcopy
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

def copy_run_format(new_run, old_run):
    # Copy basic formatting
    # new_run.bold = old_run.bold
    new_run.font.bold = old_run.font.bold
    new_run.font.cs_bold = old_run.font.cs_bold
    new_run.italic = old_run.italic
    new_run.underline = old_run.underline
    new_run.font.name = old_run.font.name
    new_run.font.size = old_run.font.size
    new_run.font.color.rgb = old_run.font.color.rgb
    
    # Copy superscript/subscript
    if old_run.font.superscript:
        new_run.font.superscript = True
    if old_run.font.subscript:
        new_run.font.subscript = True
    
    # Copy style if it exists
    if old_run.style:
        new_run.style = old_run.style
    
        # Explicitly set bold at the XML level
    if old_run.bold or (old_run.font.bold is not None and old_run.font.bold):
        b = OxmlElement('w:b')
        new_run._element.rPr.append(b)
        new_run.font.bold = True
    
    # Copy any other custom XML properties
    if old_run._element.rPr is not None:
        for child in old_run._element.rPr.getchildren():
            if child.tag not in [qn('w:t'), qn('w:br')]:  # Exclude text and line breaks
                new_child = deepcopy(child)
                if new_run._element.rPr is None:
                    new_run._element.get_or_add_rPr()
                new_run._element.rPr.append(new_child)
            
    # Copy other properties that might be relevant
    new_run.font.all_caps = old_run.font.all_caps
    new_run.font.double_strike = old_run.font.double_strike
    new_run.font.emboss = old_run.font.emboss
    new_run.font.imprint = old_run.font.imprint
    new_run.font.math = old_run.font.math
    new_run.font.outline = old_run.font.outline
    new_run.font.shadow = old_run.font.shadow
    new_run.font.small_caps = old_run.font.small_caps
    new_run.font.strike = old_run.font.strike

def copy_paragraph_format(new_para, old_para):
    new_para.paragraph_format.alignment = old_para.paragraph_format.alignment
    new_para.paragraph_format.line_spacing = old_para.paragraph_format.line_spacing
    new_para.paragraph_format.space_before = old_para.paragraph_format.space_before
    new_para.paragraph_format.space_after = old_para.paragraph_format.space_after
    new_para.paragraph_format.left_indent = old_para.paragraph_format.left_indent
    new_para.paragraph_format.right_indent = old_para.paragraph_format.right_indent
    new_para.style = old_para.style

def add_formatted_text_to_cell(cell, paragraph):
    new_para = cell.add_paragraph()
    copy_paragraph_format(new_para, paragraph)
    for run in paragraph.runs:
        new_run = new_para.add_run(run.text)
        copy_run_format(new_run, run)

def create_output_document(pges):
    output_doc = Document()
    
    for page_num, page in enumerate(pges, 1):
        output_doc.add_heading(f'Page {page_num}', level=1)
        
        # Add body text
        if page[0]:
            output_doc.add_paragraph("Body Text:")
            for para in page[0]:
                new_para = output_doc.add_paragraph()
                copy_paragraph_format(new_para, para)
                for run in para.runs:
                    new_run = new_para.add_run(run.text)
                    copy_run_format(new_run, run)
        
        # Create table for columns
        if page[1] and page[2]:
            output_doc.add_paragraph("Columns:")
            table = output_doc.add_table(rows=len(page[1]), cols=2)
            table.style = 'Table Grid'
            for i, (cola_para, colb_para) in enumerate(zip(page[1], page[2])):
                add_formatted_text_to_cell(table.cell(i, 0), colb_para)
                add_formatted_text_to_cell(table.cell(i, 1), cola_para)
        
        # # Add parallels
        # if page[3]:
        #     output_doc.add_paragraph("Parallels:")
        #     for para in page[3]:
        #         new_para = output_doc.add_paragraph()
        #         copy_paragraph_format(new_para, para)
        #         for run in para.runs:
        #             new_run = new_para.add_run(run.text)
        #             copy_run_format(new_run, run)
        
        # Add page break
        output_doc.add_page_break()
    
    return output_doc
sample_table2 = create_output_document(pages_sample)
sample_table2.save('/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition Output 3.docx')

In [55]:
pages_sample[1][0][0].split()

['ממעטת',
 'על',
 'יד',
 'מעת',
 'לעת:',
 "ב'",
 'כל',
 'אשה',
 'שיש',
 'לה',
 'ווסת',
 'דייה',
 'שעתה',
 'הcמשמשת',
 'בעידין',
 'הרי',
 'זו',
 'כפקידה',
 'וממעטת',
 'על',
 '5',
 'יד',
 'מעת',
 'לעת',
 'ועל',
 'יד',
 'מפקידה',
 'לפקידה',
 "ג'",
 'שמי',
 "אומ'",
 'מקב',
 'חלה',
 'הלל',
 "או'",
 'מקביים']

In [118]:
full_file_path = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Eduyot Critical Edition.docx'
all_pages = process_document(full_file_path)

Uneven lines 0 jump 1
4 26 28 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2
3 33 33 0
3 29 12 0
Uneven lines 5 jump 0
3 25 26 5
4 30 11 0
Uneven lines 7 jump 0
3 29 30 5
Uneven lines 8 jump 1
3 25 27 4
Uneven lines 9 jump 0
3 29 30 4
Uneven lines 10 jump 0
3 33 34 3
Uneven lines 11 jump 2
3 29 32 1
Uneven lines 12 jump 1
3 28 30 1
Uneven lines 13 jump 0
4 31 32 4
Uneven lines 14 jump 1
3 30 32 4
Uneven lines 15 jump 4
3 28 33 1
Uneven lines 16 jump 3
3 26 30 4
Uneven lines 17 jump 0
3 28 29 5
Uneven lines 18 jump 0
3 28 29 1
3 27 28 0
3 38 35 0
3 31 31 0
Uneven lines 22 jump 1
3 31 33 1
Uneven lines 23 jump 0
3 25 26 1
Uneven lines 24 jump 1
5 31 33 3
Uneven lines 25 jump 0
3 27 28 9
Uneven lines 26 jump 2
3 31 34 1
Uneven lines 27 jump 0
3 29 30 4
Uneven lines 28 jump 0
3 26 27 5
Uneven lines 29 jump 1
3 30 32 4
Uneven lines 30 jump 0
3 27 28 4
Uneven lines 31 jump 1
3 29 31 4
Uneven lines 32 jump 0
3 30 31 5
Uneven lines 33 jump 0
3 30 31 4
Uneven lines 34 jump 0
3 28 29 4
3 29 28 0
Uneven lines 36 jump 0
3 28 29 3
3 33 7 0
3 28 3 0
Uneven lines 39 jump 0
5 25 26 5
Uneven lines 40 jump 2
3 28 31 4
Uneven lines 41 jump 0
4 29 30 4
Uneven lines 42 jump 0
3 32 33 1
4 30 29 0
4 23 18 0
Uneven lines 45 jump 2
3 30 33 4
3 28 19 0
3 26 1 0
3 25 18 0
Uneven lines 49 jump 0
3 29 30 2
Uneven lines 50 jump 1
3 27 29 1
Uneven lines 51 jump 0
3 29 30 3
Uneven lines 52 jump 0
3 31 32 3
Uneven lines 53 jump 1
3 30 32 3
Uneven lines 54 jump 0
3 34 35 1
3 27 27 0
Uneven lines 56 jump 0
3 28 29 3
Uneven lines 57 jump 1
3 31 33 3
Uneven lines 58 jump 1
3 29 31 5
Uneven lines 59 jump 0
3 4 5 53
Uneven lines 60 jump 0
3 30 31 4
Uneven lines 61 jump 0
3 29 30 5
Uneven lines 62 jump 0
3 30 31 3
Uneven lines 63 jump 0
2 27 28 3
Uneven lines 64 jump 0
3 31 32 5
3 26 13 0
Uneven lines 66 jump 2
3 28 31 5
Uneven lines 67 jump 0
3 32 33 3
Uneven lines 68 jump 0
3 22 23 14
Uneven lines 69 jump 0
3 31 32 3
Uneven lines 70 jump 0
3 27 28 4
Uneven lines 71 jump 0
3 27 28 5
Uneven lines 72 jump 0
3 26 27 4
Uneven lines 73 jump 0
3 31 32 2
Uneven lines 74 jump 0
3 30 31 6
Uneven lines 75 jump 0
3 28 29 6
Uneven lines 76 jump 1
3 28 30 7
3 28 15 0
Uneven lines 78 jump 0
3 24 25 5
Uneven lines 79 jump 0
3 24 25 6
Uneven lines 80 jump 0
3 31 32 5
Uneven lines 81 jump 1
3 25 27 4
Uneven lines 82 jump 0
3 33 34 2
Uneven lines 83 jump 1
3 30 32 5
Uneven lines 84 jump 1
3 25 27 6
3 30 27 0
3 26 14 0
Uneven lines 87 jump 0
3 24 25 9
Uneven lines 88 jump 3
3 28 32 5
Uneven lines 89 jump 0
3 29 30 5
Uneven lines 90 jump 0
3 27 28 2
3 29 1 0
3 30 1 0
Uneven lines 93 jump 0
5 29 30 4
3 29 21 0
4 30 4 0
3 31 1 0
Uneven lines 97 jump 0
4 27 28 6
3 28 16 0
3 28 1 0
3 31 1 0
3 27 1 0
3 29 1 0
3 30 1 0
3 24 5 0
3 28 1 0
Uneven lines 106 jump 1
3 33 35 3
Uneven lines 107 jump 0
5 29 30 3
Uneven lines 108 jump 2
3 26 29 4
Uneven lines 109 jump 0
3 26 27 7
3 25 18 0
Uneven lines 111 jump 0
3 33 34 1
Uneven lines 112 jump 0
3 33 34 1
3 27 16 0
Uneven lines 114 jump 0
3 25 26 3
Uneven lines 115 jump 0
3 23 24 6
Uneven lines 116 jump 1
4 21 23 11
Uneven lines 117 jump 1
3 27 29 4
Uneven lines 118 jump 0
4 28 29 4
Uneven lines 119 jump 1
3 28 30 5
Uneven lines 120 jump 2
3 31 34 4
Uneven lines 121 jump 0
3 24 25 12
Uneven lines 122 jump 0
3 23 24 8
Uneven lines 123 jump 0
3 28 29 9
Uneven lines 124 jump 0
3 23 24 10
3 25 10 0
Uneven lines 126 jump 0
3 33 34 4
Uneven lines 127 jump 1
3 28 30 7
3 30 5 0
Uneven lines 129 jump 1
3 27 29 4
3 22 2 0

In [111]:
for page in all_pages:
    body_txt = " ".join([p.text for p in page[0]])
    non_empty_Alines = [line.text for line in page[1] if line.text != '']
    print(len(non_empty_Alines),len(body_txt.split()))

22 38
24 36
28 33
27 35
25 31
21 35
25 36
25 32
21 24
26 24
29 35
26 25
25 24
27 29
26 32
25 27
23 27
25 28
23 25
24 30
29 28
26 30
27 37
22 24
26 39
23 32
27 31
25 35
22 28
26 34
23 34
25 34
26 31
26 32
24 34
25 34
23 45
29 33
23 30
20 38
24 30
24 29
28 36
27 31
20 25
23 29
24 33
23 25
22 22
24 29
23 31
25 28
27 28
26 30
29 32
22 26
24 31
26 28
26 33
4 35
26 31
26 32
26 32
24 26
27 37
23 25
24 31
28 30
19 24
27 35
23 37
24 26
24 27
27 29
25 32
24 33
24 30
24 33
21 27
21 29
27 28
22 28
29 32
26 28
22 24
24 33
22 34
20 35
24 25
24 30
23 34
25 33
26 33
23 32
25 34
26 35
26 32
23 25
24 36
24 32
26 40
22 38
25 31
25 36
20 32
24 32
28 35
22 37
23 24
22 33
21 33
27 34
30 27
23 31
22 24
20 24
19 20
22 25
24 33
25 29
27 32
20 33
20 30
24 33
20 26
21 32
29 31
23 30
25 37
23 31
19 26

In [123]:
lst = [1,2,3,4,5,6,7,8,9,10]
print(lst[:-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [157]:
import pandas as pd
pages_sample= process_document(sample_file_path)
page = pages_sample[0]
pd.DataFrame([[p.text for p in page[1]],[p.text for p in page[2]]])

Uneven lines 0 jump 0
4 14 15 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"\tכ""י של עדיות",29\tהרבה | מ הרב'.,\tוחכמ' | פ וחכמי' ר א ק ש יא מ ד וחכמים.,\tאומ' | פ מ או' ר ש יא אומרין ק אומרי' ד אומרים.,\tכדברי2 | מ כדב'.,,30\tאלא | מ אל'.,\tמעת |,\tממעטת | מ ממע'.,,1\tמפקידה | מ פקיד'.,\tלפקידה | מ לפקיד'.,\tומפקידה | מ ומפקי'.,\tלפקידה | ר לפקיד' מ לפקי'.,None
1,מקבילות,מ הרב'.,קו פא וחכ' ר במ2 וחכמים ק ד וחכמי' מ וחכמ'.,ק אומרי' ר אומרין במ2 מ או'.,,,,מ אל'.,במ2 מע'.,מ ממעט' בו2 ממעט.,,מ ד מפקיד'.,מ ד לפקיד'.,מ ומפקי' ד ומפקיד'.,מ לפקיד'.

In [160]:
def shift_col(col,beg):
    for i in range(beg,len(col)-1):
        col[i] = col[i+1]
    col = col[:-1]
    while col[-1].text == '':
        col = col[:-1]
    print("NEW LEN",len(col))
    return col
def shift_cols(pages,sample=False):
    output_pages = []
    for ip in range(len(pages)):
        page = pages[ip]
        max_len = max(len(page[1]),len(page[2]))
        min_len = min(len(page[1]),len(page[2]))
        print(ip,max_len,min_len)
        print("B",[p.text for p in page[2]])
        lastBblank= 0
        print("A",page[1][0].text)
        for i in range(min_len):
            if i > len(page[1])-1 or i > len(page[2])-1:
                break
            if page[2][i].text == '' and page[1][i].text != '':
                lastBblank = i
            if page[1][i].text == '' and page[2][i].text != '':
                print("Empty A line",i,"Last B blank",lastBblank)
                page[2] = shift_col(page[2],lastBblank)
        # if len(page[2])> len(page[1]):
        #     print("Extra B lines",len(page[2])-len(page[1])," Last B blank",lastBblank)
        #     shift_col(page[2],lastBblank)
        #     page[2] = page[2][:len(page[1])]
        if sample:
            print(len(page[1]),len(page[2]))
            df = pd.DataFrame([[p.text for p in page[1]],[p.text for p in page[2]]])    
            return df
shift_cols(pages_sample,sample=True)

0 14 14
B ['מקבילות', "מ הרב'.", "קו פא וחכ' ר במ2 וחכמים ק ד וחכמי' מ וחכמ'.", "ק אומרי' ר אומרין במ2 מ או'.", '', '', "מ אל'.", "במ2 מע'.", "מ ממעט' בו2 ממעט.", '', "מ ד מפקיד'.", "מ ד לפקיד'.", "מ ומפקי' ד ומפקיד'.", "מ לפקיד'."]
A 	כ"י של עדיות
14 14

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"\tכ""י של עדיות",29\tהרבה | מ הרב'.,\tוחכמ' | פ וחכמי' ר א ק ש יא מ ד וחכמים.,\tאומ' | פ מ או' ר ש יא אומרין ק אומרי' ד אומרים.,\tכדברי2 | מ כדב'.,,30\tאלא | מ אל'.,\tמעת |,\tממעטת | מ ממע'.,,1\tמפקידה | מ פקיד'.,\tלפקידה | מ לפקיד'.,\tומפקידה | מ ומפקי'.,\tלפקידה | ר לפקיד' מ לפקי'.
1,מקבילות,מ הרב'.,קו פא וחכ' ר במ2 וחכמים ק ד וחכמי' מ וחכמ'.,ק אומרי' ר אומרין במ2 מ או'.,,,מ אל'.,במ2 מע'.,מ ממעט' בו2 ממעט.,,מ ד מפקיד'.,מ ד לפקיד'.,מ ומפקי' ד ומפקיד'.,מ לפקיד'.

In [161]:
all_pages = process_document(full_file_path,verbose=False)
shift_cols(all_pages)
table_all2 = create_output_document(all_pages)
table_all2.save('/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Eduyot Critical Edition Output Table 2.docx')

Uneven lines 0 jump 1
Uneven lines 1 jump 0
Uneven lines 2 jump 0
Uneven lines 5 jump 0
Uneven lines 7 jump 0
Uneven lines 8 jump 1
Uneven lines 9 jump 0
Uneven lines 10 jump 0
Uneven lines 11 jump 2
Uneven lines 12 jump 1
Uneven lines 13 jump 0
Uneven lines 14 jump 1
Uneven lines 15 jump 4
Uneven lines 16 jump 3
Uneven lines 17 jump 0
Uneven lines 18 jump 0
Uneven lines 22 jump 1
Uneven lines 23 jump 0
Uneven lines 24 jump 1
Uneven lines 25 jump 0
Uneven lines 26 jump 2
Uneven lines 27 jump 0
Uneven lines 28 jump 0
Uneven lines 29 jump 1
Uneven lines 30 jump 0
Uneven lines 31 jump 1
Uneven lines 32 jump 0
Uneven lines 33 jump 0
Uneven lines 34 jump 0
Uneven lines 36 jump 0
Uneven lines 39 jump 0
Uneven lines 40 jump 2
Uneven lines 41 jump 0
Uneven lines 42 jump 0
Uneven lines 45 jump 2
Uneven lines 49 jump 0
Uneven lines 50 jump 1
Uneven lines 51 jump 0
Uneven lines 52 jump 0
Uneven lines 53 jump 1
Uneven lines 54 jump 0
Uneven lines 56 jump 0
Uneven lines 57 jump 1
Uneven lines 58 jump 1
Uneven lines 59 jump 0
Uneven lines 60 jump 0
Uneven lines 61 jump 0
Uneven lines 62 jump 0
Uneven lines 63 jump 0
Uneven lines 64 jump 0
Uneven lines 66 jump 2
Uneven lines 67 jump 0
Uneven lines 68 jump 0
Uneven lines 69 jump 0
Uneven lines 70 jump 0
Uneven lines 71 jump 0
Uneven lines 72 jump 0
Uneven lines 73 jump 0
Uneven lines 74 jump 0
Uneven lines 75 jump 0
Uneven lines 76 jump 1
Uneven lines 78 jump 0
Uneven lines 79 jump 0
Uneven lines 80 jump 0
Uneven lines 81 jump 1
Uneven lines 82 jump 0
Uneven lines 83 jump 1
Uneven lines 84 jump 1
Uneven lines 87 jump 0
Uneven lines 88 jump 3
Uneven lines 89 jump 0
Uneven lines 90 jump 0
Uneven lines 93 jump 0
Uneven lines 97 jump 0
Uneven lines 106 jump 1
Uneven lines 107 jump 0
Uneven lines 108 jump 2
Uneven lines 109 jump 0
Uneven lines 111 jump 0
Uneven lines 112 jump 0
Uneven lines 114 jump 0
Uneven lines 115 jump 0
Uneven lines 116 jump 1
Uneven lines 117 jump 1
Uneven lines 118 jump 0
Uneven lines 119 jump 1
Uneven lines 120 jump 2
Uneven lines 121 jump 0
Uneven lines 122 jump 0
Uneven lines 123 jump 0
Uneven lines 124 jump 0
Uneven lines 126 jump 0
Uneven lines 127 jump 1
Uneven lines 129 jump 1
0 28 26
B ['מקבילות', 'ר מ ד ירו פסיו במ2 בו21 שמאי ק שמיי.', "פא מ ירל במ2 או'.", "קו פא ר ק ירל·ו פסיל·ו במ2 בו21 הנשים מ ד הנשי'.", 'ד דין.', '', 'קו פא ר ק ד ירל·ו בו1 הלל מ במ2 הילל בו2 והלל.', '', "קו אומ' ר ק אומר.", "מ מפקי'.", "מ לפקי'.", "ר במ2 ואפי' בו21 ואפילו מ ירל אפי'.", "מ ד לימי'.", '', "מ הרב'.", "קו פא וחכ' ר במ2 וחכמים ק ד וחכמי' מ וחכמ'.", "ק אומרי' ר אומרין במ2 מ או'.", '', '', '', "מ אל'.", "במ2 מע'.", "מ ממעט' בו2 ממעט.", '', "מ ד מפקיד'.", "מ ד לפקיד'.", "מ ומפקי' ד ומפקיד'.", "מ לפקיד'."]
A 	כ"י של עדיות
Empty A line 12 Last B blank 7
NEW LEN 27
Empty A line 21 Last B blank 18
NEW LEN 26
1 30 29
B ['מקבילות', 'בו2 ממעט.', '', 'קו ק וכל ד ולכל.', "מ אש'.", '', '', 'מ ד בו וסת.', 'ד בו דיה.', "מ שעת'.", "קו ק ד והמשמשת פא ר ירל פסיל·ו ירו בו פסבו והמשמשת מ והמשמ' [פסבמ|המשמש'].", '', '', "קו בעידים פא בעדין ר ק ד ירל·ו פסיל·ו בו פסבמ·ו בעדים מ בעדי'.", '', "פא ירל·ו הממעטת ק ד ממעטת מ ממעט'.", '', '', "מ מפקיד'.", '', '', '', 'תו שמיי תע במ בו שמאי.', "תו במ או'.", 'תו כקב.', '', 'תו בית הלל תע במ והילל בו והלל.', "תו·ע אומ'.", 'תו מקבים.', '']
A 	כת"י של עדיות
Empty A line 13 Last B blank 12
NEW LEN 28
2 33 32
B ['מקבילות', 'תו במ וחכמים.', '', "תו·ע אומ'.", '', '', '', '', 'תו חיב תע בו חייב.', '', 'במ·ו משהגדילו.', '', '', 'במ·ו המדות.', 'במ אמרו חכמים.', '', 'במ·ו רבעים קמח.', '', 'במ·ו חייבין בחלה.', '', '', 'במ·ו יוסי.', "במ או'.", '', '', '', '', '', '', 'תע הילל.', "תע אומ'.", '', '']
A 	כת"י של עדיות
3 33 33
B ['מקבילות', 'תו·ע מים שאובין של שנים עשר לוג.', '', 'בו שאובים.', 'בו פוסלים.', 'תו·ע במ·ו המקוה.', '', 'תו·ע ().', '', 'במ·ו שחייב אדם.', 'במ לומר.', 'במ·ו בלשון.', 'תו שמיי תע במ·ו שמאי.', "תו במ או'.", '', 'תו·ע מלא הין מים שאובין של ששים <תע|שלשים> וששה לוג.', 'במ·ו תשעה.', 'במ·ו קבין.', 'תו במ וחכמים.', "תו במ או'.", '', '', '', 'במ·ו ().', 'תו·ע מעשה שבאו.', '', 'תו גרדיין.', 'בו האשפה.', 'בו שבירושלים.', '', 'תו בשם תע במ·ו משום.', 'תו·ע במ·ו שמעיה.', '']
A 	כת"י של עדיות
Empty A line 16 Last B blank 8
NEW LEN 31
Empty A line 22 Last B blank 21
NEW LEN 30
Empty A line 26 Last B blank 23
NEW LEN 29
4 29 12
B ['מקבילות', 'תו·ע במ ששלשת בו ששלשה.', '', 'תו·ע במ·ו לוגין.', '', '', 'בו פוסלים.', '', 'תו·ע במ·ו המקוה.', "תע וקיימו חכמ' במ·ו וקיימו חכמים.", 'תו·ע במ·ו דבריהם.', '']
A 	כת"י של עדיות
Empty A line 6 Last B blank 5
NEW LEN 10
5 26 25
B ['מקבילות', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'ירל1 ירו1 במ65321 בו654321 אין.', 'במ65321 ב"ד.', 'ירל421 ירו421 במ65321 בו654321 ().', '']
A 	כת"י של עדיות
6 30 11
B ['מקבילות', 'במ65321 ב"ד.', 'במ5 בו43 חברו.', 'ירל3 ירו3 בו621 אלא אם כן במ521 בו543 אלא א"כ במ63 אל\' א"כ.', '', '', 'במ53 בו6543 הימנו.', '', "במ53 בחכמ'.", 'ירו4 במ65321 ובמניין בו654321 ובמנין.', '']
A 	כת"י של עדיות
Empty A line 8 Last B blank 7
NEW LEN 9
7 30 29
B ['מקבילות', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'ירל·ו יאמרו.', '', '', 'ירל·ו כדברי.', "ירל ר' איש ירו רבי איש.", '', 'ירל·ו שמעת.', '', 'במ ב"ש בו בש"א.', '', '', '', "במ עצמו' בו עצמות.", '', 'במ העצמין.']
A 	כת"י של עדיות
Empty A line 23 Last B blank 22
NEW LEN 29
8 27 25
B ['מקבילות', 'במ·ו או.', "במ משני'.", 'במ·ו או.', "במ משלש'", '', 'במ וב"ה.', '', '', '', '', '', 'במ ().', 'בו ().', 'במ·ו הגויה.', '', '', '', 'במ הבניין בו בנין.', 'במ המניין בו מנין.', 'במ·ו שמאי.', "במ או'.", '', "במ אפי'.", "במ עצם אחד מן השדר' או מן הגלגלת בו עצם מן השדרה או מן הגולגולת.", '', 'ר מ ד ירל·ו כרשיני.']
A 	כת"י של עדיות
Empty A line 14 Last B blank 11
NEW LEN 26
Empty A line 19 Last B blank 16
NEW LEN 25
Empty A line 22 Last B blank 20
NEW LEN 24
9 30 29
B ['מקבילות', "מ תרומ'.", 'ר מ ירו ב"ש.', 'ק שמיי ש ד שמאי.', "ר () ק פא ש ירל אומ' ד אומרים.", '', 'פא ש מ ד ירל·ו שורין ר שרים.', 'ר ש מ ד ירל·ו ושפין.', '', "מ בטהר'.", '', 'קו ומאכילים.', 'ק בטמאה.', 'ר מ וב"ה.', 'קו ובית ש בית.', '', '', "פא ר ירל אומ' ק אומרי' ש אומרין ד אומרים.", 'פא ש מ ד ירל·ו שורין.', "מ בטהר'.", 'ר ש מ ד ירל·ו ושפין תו וטפין תע שפין.', '', '', 'ק בטמאה.', 'ר ש ד שמאי ק שמיי מ ב"ש.', "ק ש אומ' ד אומר.", "פא ייאכלו מ יאכל'.", '', "ק ור'.", "קו פא ר ק ש ירל·ו עקיבה ד עקיבא מ עקי'."]
A 	כת"י של עדיות
Empty A line 7 Last B blank 5
NEW LEN 29
10 34 33
B ['מקבילות', "קו ש אומ' ק ד אומר.", 'קו ק מ מעשיהם.', '', '', '', "ק הפוריט במ2 הפוד'.", '', "במ3 סל'.", "מ במ321 ממעו'.", 'קו פא ר ק ש מ ד ירל321 ירו321 במ4321 בו4321 ().', "ר במ32 מעש'.", 'קו ש מ ד ירו321 במ4321 בו4321 שני.', 'קו פא ר ק ש מ ד ירל·ו במ32 בו32 ().', '', 'ר מ במ32 ב"ש.', 'ק שמיי ש ד ירו בו32 שמאי.', "קו פא ר ק ש ד אומ'.", 'קו פא ר מ ירל·ו במ32 בו32 בכל.', "במ32 הסל'.", "במ32 מעו'.", 'קו ובית הלל ר ב"ה מ במ32 וב"ה.', '', "קו פא ר ד ירל אומ' ק אומרי' ש אומרין.", "קו פא ר ירל·ו במ2 בו32 בשקל במ3 בשק'.", "במ32 כס'.", "קו פא ר ירל·ו ובשקל במ32 בשק' בו32 בשקל.", "במ32 מעו'.", '', '', "פא ר ק ש אומ'.", '', "קו פא ר ק ש מ ירל·ו ופירות ד ופירו'.", 'ק ש מ ירל·ו כסף.']
A 	כת"י של עדיות
Empty A line 6 Last B blank 5
NEW LEN 33
11 32 29
B ['מקבילות', "ר ק וחכמי' ש ד וחכמים.", "ק מתירי'.", '', '', 'ק הפוריט.', '', '', 'קו פא ש ר ירל שלמעשר. ', '', "במ מעש'.", 'קו ק מ ד ירו במ·ו שני.', "במ בירושל' בו בירושלים.", 'ר מ במ ב"ש.', 'ק שמיי ש ד ירו בו שמאי.', '', "פא ר ק ש מ ד ירל אומ'.", '', 'ק ד כל.', '', "במ מעו'.", 'קו ובית הלל ר ב"ה מ במ וב"ה.', '', '', "ק אומרי' מ במ או'.", 'קו פא ר ירל·ו במ·ו בשקל.', "במ כס'.", '', "קו פא ר ירל·ו ובשקל במ בשק' מ בו בשקל.", "במ מעו'.", 'ק והדנין ש ד הדנין.', "פא ש חכמים ר ק ד חכמי'."]
A 	כת"י של עדיות
Empty A line 13 Last B blank 9
NEW LEN 31
Empty A line 24 Last B blank 22
NEW LEN 30
12 30 28
B ['מקבילות', "פא ק ר ירל אומ' ש אומרין ד אומרי'.", '', "מ שלש'.", "קו פא דינרים ק דינרי' מ דינר' ד דינר ירל דינ' ירו דינרי.", '', 'ד ודינר.', '', '', '', "קו פא ר ש ק מ ד ירל ר' ירו רבי.", "ק עקיב' מ עקי' ד עקיבא.", "פא אומר ר ק ש ד אומ'.", 'ד שלשה.', "קו דינרים ק מ דינרי' ד דינרים.", '', 'ד ().', 'קו ורבעת פא ר מ ירל·ו וברביעית ק וברביעת ש וברבעת.', '', 'ירו ().', "קו פא ש וברבעת ר וברביעית ק וברביעת מ וברביעי' ד ורביעיות.", '', '', "קו ר ק ש מ ד ירל ר' פא ירו רבי.", '', "ר ק ש ד אומ'.", 'פא ר ק ש מ ארבעה ד ירו ארבע ירל ארבע.', '', 'מ אצטרי ירל·ו אספרו.', 'ר ש מ ד שמאי ק שמיי.']
A 	כת"י של עדיות
Empty A line 14 Last B blank 9
NEW LEN 29
13 32 31
B ['מקבילות', "ר ק ש ד אומ'.", 'קו פא ש מ ד ירו יניחנה ר ק יניחנו.', '', 'קו פא ר ק ש מ ד ירל·ו ויאכל.', 'ר כנגדן.', '', '', 'ק מג ד של כלה.', 'ד שנטל.', 'קו ר ק ד חפוייו ר חיפוייו מג חיפיו.', '', 'מג ב"ש.', "ד בי'.", 'ר ד שמאי ק שמיי.', "ר ד מטמאין ק מטמאים מג מטמ'.", 'קו ובית הלל מג וב"ה.', 'ק מטהרים.', '', 'ר מג ד שמאי ק שמיי.', "קו פא ר או' אומר.", 'קו פא ר ק מג ד מלבן.', 'ק מג ד של כסא.', '', '', '', "ד כס'.", '', "ד בעריב'.", 'מ ב"ש.', 'ר ד שמאי ק שמיי.', 'ר מ ד מטמאין ק מטמים.']
A 	כת"י של עדיות
14 32 30
B ['מקבילות', 'מ וב"ה.', '', 'ר מ ד שמאי ק שמיי.', "קו ק ר ד אומ'.", 'מ ().', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', "מ ואמר' במ31 בו31 שאמרה.", 'ירל·ו בעלה.', '', 'ר ש מ ד במ31 בו321 תנשא.', 'ירו בעל.', '', '', "קו פא ר ק ש ד ירל·ו תתיבם מ תתיב' תע במ31 בו321 תתייבם.", 'קו בית הילל פא ק ש ד ירל·ו בו בית הלל ר מ ב"ה תע ובית הילל.']
A 	כת"י של עדיות
Empty A line 24 Last B blank 22
NEW LEN 31
15 33 28
B ['מקבילות', "פא ר ק ירל אומ' ש אומרין ד אומרים.", '', "מ אל'.", "ר ירל·ו בבואה מ בבא' תע הבא.", "מ הקצי'.", '', "מ בלב' בו ובאותה מדינה וכמעשה שהיה.", '', '', 'קו פא ש ד בו להם.', 'ר מ ב"ש.', 'ק שמיי ש ד ירו בו שמאי.', 'קו פא מ ירל·ו אחד.', "מ הבא' ד באה.", '', '', '', '', '', "מ הקצי'.", "קו ואחד מן פא ירל ואחד מ ואח' ירו ואחה.", "מ הבא' ד באה.", "קו פא ש ד ירל·ו בו הזיתים ר ק הזתים מ הזתי'.", '', '', 'בו ואחת הבאה מן הבציר ואחת.', "קו פא ירל·ו ואחד מ ואח'.", "מ הבא' ד באה.", 'בו ממדינה למדינה.', "מ ממדינ'.", 'ר ולא.', 'ר ק ש מ ד דברו בו דברו חכמים.']
A 	כת"י של עדיות
Empty A line 5 Last B blank 2
NEW LEN 32
Empty A line 20 Last B blank 18
NEW LEN 31
16 30 26
B ['מקבילות', "מ בקצי'.", "מ אל'.", 'ד בהוה.', 'מ וחזרו.', 'קו בית הילל ר מ ב"ה.', '', "קו פא ר ק ש בו להורות מ להודו'.", '', 'קו בו ().', 'קו כבית שמי ר מ ב"ש בו כבית שמאי.', 'ק שמיי ש ד ירו בו שמאי.', '', '', 'ר מ ב"ש.', '', 'ק שמיי ש ד ירו פסיו בו שמאי.', "קו מ או' ש אומרין ד אומרים.", '', "ר ש ד בו תנשא ותטול מ תנש' ותטול.", "ר כתוב' בו כתובתה.", 'קו בית הילל ר מ וב"ה ק ש בו בית הלל.', '', "פא ר ק ירל1 אומ' ש אומרין ד אומרים.", '', "ר ש ד בו תנשא מ תנש'.", '', "ר ש ד בו תטול מ תטו'.", "מ כתוב' בו כתובתה.", "ר אמר'."]
A 	כת"י של עדיות
Empty A line 19 Last B blank 18
NEW LEN 29
17 29 28
B ['מקבילות', 'קו פא ש מ ד בו להם ירו להו.', '', '', 'ר מ ב"ש.', 'ק שמיי ש ד ירו בו שמאי.', 'פא ר ש מ ד בו התרתם.', '', 'בו ().', 'קו ר ק ש מ ד ירל1 ירו הערוה בו ערוה.', '', '', "מ החמור' ד בו חמורה.", 'פא ר ש לא.', 'בו נתיר.', 'בו ().', "מ הממו' בו ממון.", '', "ר אמ'.", 'קו פא ש ד בו להם.', 'ר מ ב"ה.', 'תע הילל.', 'קו מציאנו ק תו מצאנו.', 'ק מ תע ירל·ו בו האחין תו ארץ.', '', 'קו ר ק ש מ תו ירל·ו בו נכנסין פא ד תע נכנסים.', '', "קו פא ר ק ש ד תו·ע ירל·ו בו לנחלה מ לנחל'.", '']
A 	כת"י של עדיות
Empty A line 8 Last B blank 7
NEW LEN 27
Empty A line 14 Last B blank 10
NEW LEN 26
Empty A line 21 Last B blank 15
NEW LEN 25
18 29 28
B ['מקבילות', 'ק תו שמיי ש ד תע ירו בו שמאי.', 'תע ().', '', "מ כתובת' תו כת' בו כתובה.", "פא נילמד ר ק תע ירל21 ירו21 בו נלמוד מ מלמ' ירו3 מלמד.", "תו שכת' תע שכתוב בה.", "קו שהיא מ שהו' ד שכך.", '', '', 'מ () ', 'תו לכשתנשאי תע לכשתתפיסי ותינשא.', 'קו פא ק ירל321 ירו321 תינשאי ר ש מ בו תנשאי.', 'פא ש מ ד תו בו תטלי תע טולי.', '', "ק מ שכתו' תו שכת'.", 'ר מ ירל3 ירו3 בו ליכי תו ליכי בכתובתיך תע בכתובתיך.', '', 'פא ד תע בו וחזרו.', 'ר מ ב"ה.', 'תע הילל.', 'קו פא ר ק ש ד תע ירל3 ירו3 בו להורות מ תו ירל21 ירו21 להודות.', '', 'מ ().', 'ר בו ב"ש מ כב"ש.', 'ק תו שמיי ש ד תע ירו321 שמאי.', '', '', '']
A 	כת"י של עדיות
Empty A line 6 Last B blank 3
NEW LEN 25
Empty A line 9 Last B blank 8
NEW LEN 24
Empty A line 22 Last B blank 20
NEW LEN 23
19 28 27
B ['מקבילות', "מ עב'.", 'קו פא ר ק ש מ ד ירל·ו במ5432 בו54321 חורין.', "מ עוב'.", '', '', '', "מ אח'.", '', "במ4 אח'.", '', "פא דב' מ ירל·ו במ5432 בו54321 דברי ד בדברי.", 'קו במ32 בית הילל ר מ במ54 ב"ה.', '', '', 'ר במ5 אמרו להן ב"ש ד בו53 אמרו להם בית שמאי.', 'מ במ4 ב"ש.', 'ק שמיי ש ד במ32 בו32 שמאי.', "ש אומרין מ במ4 או' במ2 ().", 'ר ש מ ד ירו במ5432 בו4321 תקנתם.', 'בו4 את. ', '', '', "ר ש מ ד ירו במ5432 בו4321 תקנתם במ4 תקנת'.", "מ במ4 ליש'.", "מ במ54 שפח'.", 'בו1 אי אפשר.', '']
A 	כת"י של עדיות
Empty A line 12 Last B blank 10
NEW LEN 26
20 38 35
B ['מקבילות', "במ3 יכול מפני צד חירות שבו במ4 יכול משו' בת חורי' שבו בו21 יכול שכבר חציו בן חורין.", "במ4 יכו'. ", "מ ליש' בת במ4 וליש' בת בו41 לישא בת. ", 'ק ובת.', "קו פא ר ש ד ירל·ו במ532 בו54321 חורין מ במ4 חורי'.", 'בו1 אי אפשר. ', "מ אי'.", "במ43 יכול מפני <במ4|משו'> צד עבדות <במ4|עבדו'> שבו בו21 יכול שכבר <בו2 שעדיין> חציו עבד.", 'ר במ4 בו3 ליבטל ש יבטל מפריה ורביה במ5 ().', '', "במ4 והלא כל העול' כלו", '', "פא ר ק ש מ ד ירל·ו במ532 בו54321 נברא במ4 נבר'.", "מ במ5 העול'.", "מ אל'.", "ר ק ש ד במ2 בו54321 לפריה מ במ54 לפרי' במ3 לפרייה.", '', "פא ק ירל·ו ורבייה ר ש ד במ32 בו54321 ורביה מ במ54 ורבי'.", '', 'ד בו54321 שנאמר ', 'במ5 שנאמר כה אמר יי יוצר הארץ ועושה והוא כוננה.', 'פא ר ק ש מ ירו במ5432 בו432 תהו.', "מ במ4 ברא'.", '', "מ במ4 יצר'.", '', '', 'ר במ4 בו4 ().', 'ש מ ד במ532 תקון.', "מ העול'.", "במ4 כופי'.", "במ4 אותו מפני תקון העול'.", "מ במ5 ועוש'.", '']
A 	כת"י של עדיות
Empty A line 2 Last B blank 0
NEW LEN 33
Empty A line 10 Last B blank 9
NEW LEN 32
Empty A line 11 Last B blank 9
NEW LEN 31
Empty A line 20 Last B blank 16
NEW LEN 30
Empty A line 21 Last B blank 16
NEW LEN 29
Empty A line 24 Last B blank 22
NEW LEN 28
21 31 31
B ['מקבילות', 'פא אתו.', 'פא ר ק ש מ ד ירל·ו במ532 בו54321 חורין.', "מ וכות' בו3 וכותב לו בו4 וכותבין במ2 ועושה.", '', '', '', 'מ במ532 בו54321 וחזרו.', 'ר מ במ5 ב"ה.', 'במ32 בו2 הילל.', "פא ר ק ש ד במ3 בו54321 להורות מ להודו'.", 'מ במ32 בו2 ().', '', 'ר במ5 ב"ש מ כב"ש במ2 כבי\' שמאי במ3 בו2 כבית שמאי.', '', '', 'ק שמיי ש ד ירו במ32 בו32 שמאי.', '', '', '', '', '', 'במ·ו דברי.', '', 'במ הילל.', '', 'בו ב"ש.', 'במ שמאי.', '', '', 'יו\t"כלי חרס ... לך ולו (שו\' 16)"  בבלי חגיגה כב.']
A 	כת"י של עדיות
Empty A line 16 Last B blank 15
NEW LEN 30
Empty A line 21 Last B blank 20
NEW LEN 29
22 33 31
B ['מקבילות', '', 'במ האוכלין בו אוכלים.', '', 'במ המשקין .', '', '', 'במ חרס שבתוכו.', '', '', 'בו להם.', 'במ·ו ב"ה לב"ש.', '', 'במ מפני מה אינו מציל על הכל.', '', '', 'במ להם בו ().', 'במ ב"ש.', '', 'במ ().', '', 'במ שמטמא.', '', '', '', '', '', '', '', 'במ·ו להם.', 'במ ב"ה.', '', 'במ טהרתם.']
A 	כת"י של עדיות
Empty A line 4 Last B blank 3
NEW LEN 32
Empty A line 12 Last B blank 11
NEW LEN 31
23 26 25
B ['מקבילות', 'במ·ו אוכלין.', '', 'במ ומשקין וכלי חרס.', '', '', "במ אמ'.", 'בו להם.', 'במ·ו ב"ש.', '', '', 'במ כשטהרנו.', '', 'במ ().', 'בו אוכלין.', '', 'בו ומשקין.', '', '', 'במ·ו טהרנו.', '', 'במ·ו נטהר.', '', '', '', 'במ שטהרנו בו שטהרתו.']
A 	כת"י של עדיות
Empty A line 8 Last B blank 5
NEW LEN 25
24 33 31
B ['מקבילות', '', '', '', '', '', '', '', 'פא ש ד חנינה מ בו חנינא.', '', '', '', '', "פא ש ירל·ו מימיהן מ מימיה'.", "קו פא ר ש ירל שלכהנים מ של כהני'.", 'קו פא ר ק ש מ ד ירל·ו בו נמנעו.', '', "מ מלשרו'.", '', 'ר ק ש מ ד בו שנטמא.', 'ר ש מ ד בולד.', '', "ר הטומא'.", 'ירל בשר.', 'פא ר ש מ ד בו שנטמא.', '', '', '', 'ר מ ירל אע"פ ד אעפ"י.', "קו שמוסיפין פא ר ש ד ירל·ו בו שמוסיפין מ שמוסי'.", '', 'בו ().', "קו טומאה מ טומא'."]
A 	כת"י של עדיות
25 28 27
B ['מקבילות', '', '', '', '', "מ עקיבא ואמ' בו עקיבא ואמר.", "פא עקיב' מ ד פסבמ בו פסבו עקיבא.", '', 'קו ש ירל·ו פסבו מימיהן.', "ק מ ד ירו בו פסבו של כהנים ד של כהני'.", '', 'קו פא ר ש מ ד ירל·ו בו פסבו נמנעו.', '', '', "פא השמן °בנר° מ השמ'.", 'פא ר ש מ ד ירל·ו בו שנפסל.', '', 'קו פא ר ק ש מ ד ירל·ו בו בטבול.', '', '', 'פא ר ש מ ד בו שנטמא.', '', 'ר מ ירל אע"פ ד אעפ"י.', 'קו שמוסיפין פא ר ש מ ד ירל·ו בו שמוסיפין.', '', '', 'בו ().', 'קו טומאה.']
A 	כת"י של עדיות
Empty A line 6 Last B blank 4
NEW LEN 27
26 34 31
B ['מקבילות', 'מ בו חנינא ד חנינה.', "מ הכהני'.", 'ק ש מ ד בו מימי.', '', '', 'ד יצא בו שיוצא.', '', '', 'מ א"ר.', 'ק ד אמר.', '', "פא ר עקיב' מ עקי' ד בו עקיבא.", '', '', '', 'קו פא ר ק ש מ ד בו שהמפשיט.', '', '', '', 'קו פא ר ק ש מ ד בו ונמצא.', '', 'פא ש מ ד טרפה.', 'ק שייאותו מ יאותו.', '', 'בו | בעורה.', '', "ר ש ד וחכמים ק וחכמי'.", '', "קו מ או' ק אומרי' ש אומרין ד אומרים.", '', 'קו () ר ק ש מ בו אין.', 'ר ק ש מ ראיתי.', 'קו פא ראייה.']
A 	כת"י של עדיות
27 30 29
B ['מקבילות', "קו ר יוצא ד יוצ'.", '', 'ק השרפה.', '', "במ הו'.", '', '', "במ שהו'.", "במ ירושל' בו ירושלים.", '', '', '', '', 'במ בה.', '', '', 'במ·ו מלוה. ', '', '', '', '', '', 'במ·ו ואחרים.', 'בו חותמים.', '', '', 'בו חכמים.', '', 'בו והכשירוהו.']
A 	כת"י של עדיות
Empty A line 17 Last B blank 16
NEW LEN 29
28 27 26
B ['מקבילות', "מ במ2 (ש)האש' בו2 אשה.", "מ במ2 כותב'.", '', "ר ש ד גטה מ במ2 גיט'.", '', '', "מ במ2 כות'.", 'ש ().', 'ד שברו.', "ש קייום מ קיו'.", '', "מ במ2 אל'.", '', 'במ·ו מחט.', '', 'במ·ו שנמצאת.', '', '', 'במ הסכין.', 'במ·ו והידים.', '', '', 'במ הבשר.', '', 'במ·ו ().', 'במ·ו נמצאת.']
A 	כת"י של עדיות
Empty A line 20 Last B blank 18
NEW LEN 26
29 32 30
B ['מקבילות', 'במ ב[  ]ש', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'ד היה.', '', 'קו פא ר ק מ ד אינה.', 'ר ד חבור.']
A 	כת"י של עדיות
30 28 27
B ['\tמקבילות', 'קו שיבלת ק ירל·ו שיבולת ד שבלת.', '', 'מ מאשה.', '', 'ק ש בקמה.', '', '', 'ק מן.', '', '', '', 'קו ר ד ה ירל·ו הרי היא.', 'ר של-בעל קו פא ש ירל שלבעל.', '', '', 'קו ר ד ה ירל·ו הרי היא.', 'ק מ ד ה ירו של עניים.', 'ירל·ו על.', '', '', '', '', '', 'ירל·ו מלא.', 'ירל·ו סלו.', '', 'ירל·ו ומלוא.']
A 	כת"י של עדיות
Empty A line 13 Last B blank 11
NEW LEN 27
31 31 29
B ['מקבילות', 'ירל·ו סלו.', '', '', '', '', '', "תו ג'.", 'תו·ע דברים.', '', '', 'תו·ע ישמעאל.', "תו אחד תע אמ'.", 'תע להן.', 'תו·ע איסור.', '', 'תו·ע והיתר.', '', '', 'תו·ע ופירשן.', "תו ר' יהושע.", '', 'תו·ע מתיא.', 'תו המפיש תע ירל·ו המיפיס במ321 בו321 המפיס.', '', '', 'תו·ע ירל·ו במ321 בו321 מורסא.', '', 'תו לקולפה ולעשות תע לקולפה או לעשות.', '', 'תו·ע פה כדרך שהרופאין (תע|שהרופאים) עושין.']
A 	כת"י של עדיות
Empty A line 16 Last B blank 15
NEW LEN 30
Empty A line 22 Last B blank 20
NEW LEN 29
32 31 30
B ['מקבילות', 'תו·ע ירל·ו במ321 בו21 אם.', '', "במ3 ממנ'.", 'ירל·ו הליחה בו3 ליחה.', '', '', '', '', 'במ1 מתעסק במ2 בו21 מתעסק בו.', '', 'ירל·ו במ21 בו21 ישכנו.', '', 'ירל·ו בו21 אם.', '', '', '', 'ירל2 ירו2 על.', 'במ אילפסין בו אלפסין.', '', 'ירל1 עירניות ירל1ג ס"א ארוניות במ חירניות בו חרניות.', 'במ ().', '', '', '', '', '', '', '', '', 'במ·ו אליעזר.']
A 	כת"י של עדיות
Empty A line 21 Last B blank 19
NEW LEN 30
33 31 30
B ['מקבילות', 'ירל2 ביר\' ירו2 בי ר\' במ ב"ר.', "ירל2 במ או'.", 'במ·ו אף טהורות במשא הזב.', '', '', 'במ למי בו לפי.', '', 'ירל2 ירו2 במ·ו נגמרה.', '', '', '', '', '', '', '', '', '', '', '', '', 'תו·ע ירל·ו בו והבוסר במ הבוסר.', 'תו והמיילות.', '', 'בו שרסקן.', 'במ מערב שבת.', '', '', "תו·ע במ ר' ירל שהיה ר' ירו שהיה רבי בו רבי.", '', '']
A 	כת"י של עדיות
34 29 28
B ['מקבילות', "תע אומ'.", '', "ירל במ ר' ירו רבי.", 'תו·ע במ·ו עקיבא.', "תו ירל או'.", '', '', "תו ג'.", 'תו·ע דברים.', '', 'תו·ע עקיבא.', 'תו ().', '', '', 'תע משום.', '', "תו ליעזר תע אליע'.", "תו ואמ'.", '', 'תע משום.', '', 'ירל2 ירו2 בשם.', '', 'ירל2 ירו2 ליעזר.', 'ירל1 ירו1 יוצאה ירל2 ירו2 יוצא היא.', '', 'ירל21 שלזהב.', '']
A 	כת"י של עדיות
Empty A line 18 Last B blank 16
NEW LEN 27
35 29 28
B ['מקבילות', '', '', 'ירל4 ירו4 לעדות.', '', "תו אמ' תע אחד.", '', '', '', '', 'במ·ו שרץ.', 'תו החלדה תע במ·ו חולדה.', 'מ והמלכת תו·ע במ·ו וחולדה מהלכת.', '', '', '', 'קו פא ר ק מ ד תע במ·ו ככרות תו ככרים.', "ר שלתרומ' ק ד תו·ע בו של תרומה מ במ של תרומ'.", '', '', '', '', 'ד ספקו.', '', '', '', 'ח\t"ואחד משם ר\' יהושע ... ספק לא נגע"  תוספתא עדיות פ"א מ"י.', '\t"השרץ בפי ..." משנה טהרות פ"ד מ"ב   תוספתא עדיות פ"א מי"ב     בבלי חולין ט:']
A 	כת"י של עדיות
36 29 28

In [78]:
for page in all_pages:
    match_sv(page)

SV not in body כדברי2
SV not in body משנה ב
SV not in body משנה ג
SV not in body משנה ד
SV not in body שאדם חייב לומר כלשון רבו
SV not in body תשעת קבין
SV not in body משנה ה
SV not in body משנה ו
SV not in body את דברי היחיד ... שאין בית דין (שור' 27)
SV not in body ובמיניין גM
SV not in body משנה ז
SV not in body פל' גM
SV not in body שמעתה גM
SV not in body משנה ח
SV not in body בין2
SV not in body מרוב הביניין או
SV not in body הביניין גM
SV not in body משנה ט
SV not in body הלל ... בטומאה
SV not in body משנה י
SV not in body כל גM
SV not in body שקל גM
SV not in body ושקל גM
SV not in body משנה יא
SV not in body ובדינר מעות  ... בשלשה דינרין כסף (שור' 26)
SV not in body משנה יב
SV not in body שלכסא גM
SV not in body העשוי בה
SV not in body משנה יג
SV not in body תינשא גM
SV not in body אחת הבאה ... ממדינת הים (שור' 12)
SV not in body הזיתין גM
SV not in body דיברו גת
SV not in body משנה יד
SV not in body תינשא ותיטול גת
SV not in body היתרתם גת
SV not in body החמורה
SV not in body תיטלי גת
SV not in body משנה יה
SV not in body אחד1
SV not in body אחד2
SV not in body תיקנתם גת
SV not in body תיקנתם גת
SV not in body אינו יכול
SV not in body משנה יו
SV not in body חרס גת
SV not in body אכלים ומשקים שבתוכו
SV not in body בית הלל
SV not in body משנה ב
SV not in body שניטמא גת
SV not in body משנה ג
SV not in body טריפה גת
SV not in body הן גת
SV not in body משנה ד
SV not in body ירוש' גת
No variants 	מלווה גת| פא פ ר א ק ש יב ד מלוה.
SV not in body מלווה גת| פא פ ר א ק ש יב ד מלוה.
SV not in body לפי דרכך אתה למד
SV not in body משנה ה
SV not in body שלתרומה גת
SV not in body הרי ... מלוא בוצר וסלו מיכן תיזרע (שו' 25)
SV not in body תיזרע גת
SV not in body משנה ו
SV not in body ר' אלעזר ... אף במשא הזב
SV not in body משנה ז
SV not in body משנה ח
SV not in body שנים משם ... ר' יהושע (שו' 12)
SV not in body יוצא
SV not in body משנה ט
SV not in body משנה י
SV not in body משנה יא
SV not in body שלשנים עשר
SV not in body משפט גוג ... שנים עשר חודש
SV not in body משפט רשעים ... סוף המשנה
SV not in body המיטמים גJ2
SV not in body ומאהיל ... בכחצי זית (שורה 18)
SV not in body או נוגע בכחצי זית
SV not in body זית2
SV not in body ומאהיל על כשני ... מאהיל עליו (שו' 21)
SV not in body משנה ב
SV not in body הנוגיע גJ2
SV not in body על גJ2
SV not in body או ... כחצי זית (שו' 26)
SV not in body על2 ... מאהיל (שו' 25)
SV not in body על2
SV not in body על גJ2
SV not in body משנה ג
SV not in body מצטרף ... וחכ' אומ' (שורה 3)
SV not in body וחכ' אומ' מצטרף מחללין מעשר שני על אסימון דברי ר' דוסא (שורה 4)
SV not in body וחכמ' אוסרין ... דב' ר' דוסא (שורה 5)
SV not in body ידיים גJ2
SV not in body ניטמא גJ2
SV not in body משנה ד'
SV not in body משנה ה
SV not in body משנה ו
SV not in body משנה ז
No variants
SV not in body משנה ח
SV not in body אוכלת ... אני (שור' 27)
SV not in body שנישבת גJ2
SV not in body משנה ט
SV not in body הטהור עומד והטמא עובר
SV not in body טהרה ... ברשות הרבים (שור' 2)
SV not in body ספק2
SV not in body ספק3
SV not in body ספק4
SV not in body היסיט גJ2
SV not in body היסיט גJ2
SV not in body משנה י
SV not in body משנה יא
SV not in body המגרדות גJ2
SV not in body שנחלקה
SV not in body לשנים ... שנחלקה (שו' 14)
SV not in body שנחלקה
SV not in body משנה יב
SV not in body שמי גJ2
SV not in body משנה יג
SV not in body ביום טוב
SV not in body משנה יד
SV not in body שלשה ... אוסרין (שור' 1)
SV not in body יוצא
SV not in body אין מקרדין ... אבל מקרצפין
SV not in body וחכמ' ... אף לא מקרצפין (שו' 8)
SV not in body קב2
SV not in body של-ארבעת
No variants
SV not in body משנה ד
SV not in body שכחה1
SV not in body משנה ה
SV not in body חומש ואין לו
SV not in body יש לו ... אומ' (שור' 2)
SV not in body משנה ו
SV not in body אם היה ... מתחילתו
SV not in body בית שמיי
SV not in body אומ' ... ובית הלל
SV not in body ר' יהודה ... טופיח (שור' 15)
SV not in body שנתיגרשה
SV not in body מן הנשואין ומודין בנתיגרשה
No variants 	שמי פג ק שמיי ש ד שמאי.
SV not in body שמי פג ק שמיי ש ד שמאי.
SV not in body משנה ט
SV not in body כלכלת שבת ... מחייבין (שו' 16)
SV not in body משנה י
No variants
SV not in body מנזיר שלושים יום
SV not in body כתחילה גש5
SV not in body לו (בגליון)
No variants
SV not in body משנה יא
SV not in body יודה גש5
SV not in body משנה ב
SV not in body עים הגבינה על השלחן
SV not in body שמי גש1
SV not in body משנה ג
SV not in body בית שמיי ... מטמין (שור' 6)
SV not in body הקצח ... ובית הלל מטמים
SV not in body משנה ד'
SV not in body כרוקה וכמימי רגליה
SV not in body משנה ה'
SV not in body ומתו ... האחיות (שו' 15)
SV not in body יוציאו ר' לעזר ... (שו' 17) ובית הלל אומ'
SV not in body יהו גש1
SV not in body משנה ז
SV not in body הפקודה
SV not in body הוא ... וחכ' אוסרין (שו' 29)
SV not in body בעל מום גש2
SV not in body והיניחו גJ1
SV not in body בכרכמית גJ1 גש2
SV not in body והשקוהא גJ1
SV not in body הישקוהא גJ1
SV not in body משנה ח
SV not in body ניתנדה גJ1
SV not in body נינעלת גJ1
SV not in body בחכמה וביראות חטא
SV not in body וביראות גJ1 גש2
No variants
SV not in body ידיים גJ1
SV not in body והיניחו גJ1
SV not in body משנה ט
SV not in body חזרתה גJ1
SV not in body את1
SV not in body את2
SV not in body מצאתה גJ1 גש1
SV not in body יקרבוך
SV not in body ושניסקל גJ1
No variants 3	היין
SV not in body שניתנסך גJ1
SV not in body שלשחר גJ1
SV not in body שרבי גJ1
SV not in body משנה ג
SV not in body משנה ד
SV not in body לטמא1
SV not in body על גA גJ1
SV not in body לטמא2
SV not in body משנה ה
SV not in body כסעורה גA
SV not in body משנה ו
SV not in body ראיתה גA ג1J
SV not in body ואף גJ1
SV not in body כסעורה גJ1
SV not in body תטמא
SV not in body כזיית גJ1
SV not in body משנה ח
SV not in body ראיתה גA גJ1
SV not in body ואף ... יהי טמא (שור' 10)
SV not in body תטמא
SV not in body משנה ט
SV not in body משנה י
SV not in body טהר
SV not in body ואיבר גA
SV not in body ורובע ... ובאהל (שו' )4
SV not in body מטמים גA
SV not in body שלמת גA
SV not in body משנה יא
SV not in body משנה ב
SV not in body באהלייא גA
SV not in body שנזר
SV not in body נזיריות גA
SV not in body יום גש5
SV not in body שר' אליעז' ... וחכמ' אומ' יקרב (שו' 12)
SV not in body ואכלנוהא גA
SV not in body משנה ז
SV not in body שחיתכו גA
SV not in body הן ... עד הפורים (שורה 21)
SV not in body תניי גש5
SV not in body משנה ח
SV not in body שבסורייה
SV not in body וכשבא ... רוצה אני
SV not in body משנה ט
SV not in body סנגיי גש3
SV not in body גודגדה גA
SV not in body יוצא גש3
SV not in body מיתה גA גש3
SV not in body שיתן
SV not in body במיקצתו גA
SV not in body הוסיף רבי עקיבה
No variants

IndexError: list index out of range

In [ ]:
all_pages = process_document(full_file_path)

In [103]:
table_all = create_output_document(all_pages)
table_all.save('/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Eduyot Critical Edition Output Table.docx')

In [ ]:
def combine_cols(page):
    if len(page[1]) != len(page[2]):
        print("Uneven columns")
        return
    
    for i in range(len(page[1])):

In [204]:
def match_sv(page,sample=False):
    body = [p.text for p in page[0]]
    cola = [p.text for p in page[1][1:]] # remove the header
    # colb = page[2][1:] # remove the header
    body_txt= " ".join(body).replace("\t"," ")
    # remove any multiple spaces
    body_txt = ' '.join(body_txt.split())
    # remove digit characters
    body_txt = ''.join([i for i in body_txt if not i.isdigit()])
    body_index= 0
    remaining_body = body_txt
    body_matched=[]
    for i in range(len(cola)):
        if cola[i] == '':
            body_matched.append('')
            continue
        sv, varts = None, None
        splt = cola[i].split("|")
        if len(splt) == 1:
            sv = splt[0].strip()
        else:
            sv = splt[0].strip()
            varts = splt[1]
        if "\t" in sv:
            sv= sv.split("\t")[1]
        if "..." in sv:
            sv = sv.split("...")[0].strip()
        geniza= ['גש1', 'גש4', 'גש3', 'גש5', 'גA', 'גJ1', 'גM', 'ג3J', 'גש6', 'גJ2', 'גת']
        while len(sv.split())>1 and sv.split()[-1] in geniza:
            print(sv," Geniza??")   
            sv = " ".join(sv.split()[:-1]).strip()
        if sv and sv[-1].isdigit():
            sv = sv[:-1]
        if sv not in body_txt:
            print("SV not in body",sv)
            body_matched.append('?')
            continue
        if sv in remaining_body:
            body_index = remaining_body.index(sv)
            body_matched.append(remaining_body[:body_index+len(sv)])
            remaining_body = remaining_body[body_index+len(sv):]
        else:
            body_index= body_txt.rindex(sv)
            # print("Need to go back to index",body_index)
            body_matched.append("*")
    if sample:
        return pd.DataFrame([body_matched,cola])
pages_sample = process_document(sample_file_path)
shift_cols(pages_sample)
match_sv(pages_sample[0],sample=True)

Uneven lines 0 jump 0
4 14 15 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2
0 15 14
B ['מקבילות', "מ הרב'.", "קו פא וחכ' ר במ2 וחכמים ק ד וחכמי' מ וחכמ'.", "ק אומרי' ר אומרין במ2 מ או'.", '', '', '', "מ אל'.", "במ2 מע'.", "מ ממעט' בו2 ממעט.", '', "מ ד מפקיד'.", "מ ד לפקיד'.", "מ ומפקי' ד ומפקיד'.", "מ לפקיד'."]
A 	כ"י של עדיות
Empty A line 9 Last B blank 6
NEW LEN 14
1 30 29
B ['מקבילות', 'בו2 ממעט.', '', 'קו ק וכל ד ולכל.', "מ אש'.", '', '', 'מ ד בו וסת.', 'ד בו דיה.', "מ שעת'.", "קו ק ד והמשמשת פא ר ירל פסיל·ו ירו בו פסבו והמשמשת מ והמשמ' [פסבמ|המשמש'].", '', '', "קו בעידים פא בעדין ר ק ד ירל·ו פסיל·ו בו פסבמ·ו בעדים מ בעדי'.", '', "פא ירל·ו הממעטת ק ד ממעטת מ ממעט'.", '', '', "מ מפקיד'.", '', '', '', 'תו שמיי תע במ בו שמאי.', "תו במ או'.", 'תו כקב.', '', 'תו בית הלל תע במ והילל בו והלל.', "תו·ע אומ'.", 'תו מקבים.', '']
A 	כת"י של עדיות
Empty A line 13 Last B blank 12
NEW LEN 28
2 33 32
B ['מקבילות', 'תו במ וחכמים.', '', "תו·ע אומ'.", '', '', '', '', 'תו חיב תע בו חייב.', '', 'במ·ו משהגדילו.', '', '', 'במ·ו המדות.', 'במ אמרו חכמים.', '', 'במ·ו רבעים קמח.', '', 'במ·ו חייבין בחלה.', '', '', 'במ·ו יוסי.', "במ או'.", '', '', '', '', '', '', 'תע הילל.', "תע אומ'.", '', '']
A 	כת"י של עדיות

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,מסכזתהז עזדיזותז פר' א' הרבה,וחכמ',אומ',לא כדברי,,זה ולא כדברי זה אלא,מעת,לעת ממעטת,,על יד מפקידה,לפקידה,ומפקידה,לפקידה
1,29\tהרבה | מ הרב'.,\tוחכמ' | פ וחכמי' ר א ק ש יא מ ד וחכמים.,\tאומ' | פ מ או' ר ש יא אומרין ק אומרי' ד אומרים.,\tכדברי2 | מ כדב'.,,30\tאלא | מ אל'.,\tמעת |,\tממעטת | מ ממע'.,,1\tמפקידה | מ פקיד'.,\tלפקידה | מ לפקיד'.,\tומפקידה | מ ומפקי'.,\tלפקידה | ר לפקיד' מ לפקי'.

In [205]:
for page in pages_sample:
    match_sv(page)

SV not in body משנה ב
SV not in body משנה ג
SV not in body משנה ד

In [206]:
for page in all_pages:
    match_sv(page)

SV not in body משנה ב
SV not in body משנה ג
SV not in body משנה ד
SV not in body שאדם חייב לומר כלשון רבו
SV not in body תשעת קבין
SV not in body משנה ה
SV not in body משנה ו
ובמיניין גM  Geniza??
SV not in body משנה ז
פל' גM  Geniza??
שמעתה גM  Geniza??
SV not in body משנה ח
SV not in body מרוב הביניין או
הביניין גM  Geniza??
SV not in body משנה ט
SV not in body משנה י
כל גM  Geniza??
שקל גM  Geniza??
ושקל גM  Geniza??
SV not in body משנה יא
SV not in body משנה יב
שלכסא גM  Geniza??
SV not in body העשוי בה
SV not in body משנה יג
תינשא גM  Geniza??
הזיתין גM  Geniza??
דיברו גת  Geniza??
SV not in body משנה יד
תינשא ותיטול גת  Geniza??
היתרתם גת  Geniza??
SV not in body החמורה
תיטלי גת  Geniza??
SV not in body משנה יה
תיקנתם גת  Geniza??
תיקנתם גת  Geniza??
SV not in body אינו יכול
SV not in body משנה יו
חרס גת  Geniza??
SV not in body אכלים ומשקים שבתוכו
SV not in body בית הלל
SV not in body משנה ב
שניטמא גת  Geniza??
SV not in body משנה ג
טריפה גת  Geniza??
הן גת  Geniza??
SV not in body משנה ד
ירוש' גת  Geniza??
מלווה גת  Geniza??
SV not in body לפי דרכך אתה למד
SV not in body משנה ה
שלתרומה גת  Geniza??
תיזרע גת  Geniza??
SV not in body משנה ו
SV not in body ר' אלעזר
SV not in body משנה ז
SV not in body משנה ח
SV not in body יוצא
SV not in body משנה ט
SV not in body משנה י
SV not in body משנה יא
SV not in body שלשנים עשר
המיטמים גJ2  Geniza??
SV not in body או נוגע בכחצי זית
SV not in body משנה ב
הנוגיע גJ2  Geniza??
על גJ2  Geniza??
על גJ2  Geniza??
SV not in body משנה ג
SV not in body וחכ' אומ' מצטרף מחללין מעשר שני על אסימון דברי ר' דוסא (שורה 4)
ידיים גJ2  Geniza??
ניטמא גJ2  Geniza??
SV not in body משנה ד'
SV not in body משנה ה
SV not in body משנה ו
SV not in body משנה ז
SV not in body משנה ח
שנישבת גJ2  Geniza??
SV not in body משנה ט
SV not in body הטהור עומד והטמא עובר
היסיט גJ2  Geniza??
היסיט גJ2  Geniza??
SV not in body משנה י
SV not in body משנה יא
המגרדות גJ2  Geniza??
SV not in body שנחלקה
SV not in body שנחלקה
SV not in body משנה יב
שמי גJ2  Geniza??
SV not in body משנה יג
SV not in body ביום טוב
SV not in body משנה יד
SV not in body יוצא
SV not in body של-ארבעת
SV not in body משנה ד
SV not in body משנה ה
SV not in body חומש ואין לו
SV not in body משנה ו
SV not in body בית שמיי
SV not in body שנתיגרשה
SV not in body מן הנשואין ומודין בנתיגרשה
SV not in body שמי פג ק שמיי ש ד שמאי.
SV not in body משנה ט
SV not in body משנה י
SV not in body מנזיר שלושים יום
כתחילה גש5  Geniza??
SV not in body לו (בגליון)
SV not in body משנה יא
יודה גש5  Geniza??
SV not in body משנה ב
SV not in body עים הגבינה על השלחן
שמי גש1  Geniza??
SV not in body משנה ג
SV not in body משנה ד'
SV not in body כרוקה וכמימי רגליה
SV not in body משנה ה'
יהו גש1  Geniza??
SV not in body משנה ז
SV not in body הפקודה
SV not in body בעל מום גש
והיניחו גJ1  Geniza??
SV not in body בכרכמית גJ1 גש
והשקוהא גJ1  Geniza??
הישקוהא גJ1  Geniza??
SV not in body משנה ח
ניתנדה גJ1  Geniza??
נינעלת גJ1  Geniza??
SV not in body בחכמה וביראות חטא
SV not in body וביראות גJ1 גש
ידיים גJ1  Geniza??
והיניחו גJ1  Geniza??
SV not in body משנה ט
חזרתה גJ1  Geniza??
מצאתה גJ1 גש1  Geniza??
מצאתה גJ1  Geniza??
SV not in body יקרבוך
ושניסקל גJ1  Geniza??
שניתנסך גJ1  Geniza??
שלשחר גJ1  Geniza??
שרבי גJ1  Geniza??
SV not in body משנה ג
SV not in body משנה ד
על גA גJ1  Geniza??
על גA  Geniza??
SV not in body משנה ה
כסעורה גA  Geniza??
SV not in body משנה ו
SV not in body ראיתה גA ג1J
ואף גJ1  Geniza??
כסעורה גJ1  Geniza??
SV not in body תטמא
כזיית גJ1  Geniza??
SV not in body משנה ח
ראיתה גA גJ1  Geniza??
ראיתה גA  Geniza??
SV not in body תטמא
SV not in body משנה ט
SV not in body משנה י
SV not in body טהר
ואיבר גA  Geniza??
מטמים גA  Geniza??
שלמת גA  Geniza??
SV not in body משנה יא
SV not in body משנה ב
באהלייא גA  Geniza??
SV not in body שנזר
נזיריות גA  Geniza??
יום גש5  Geniza??
ואכלנוהא גA  Geniza??
SV not in body משנה ז
שחיתכו גA  Geniza??
תניי גש5  Geniza??
SV not in body משנה ח
SV not in body שבסורייה
SV not in body משנה ט
סנגיי גש3  Geniza??
גודגדה גA  Geniza??
יוצא גש3  Geniza??
מיתה גA גש3  Geniza??
מיתה גA  Geniza??
SV not in body שיתן
במיקצתו גA  Geniza??
SV not in body הוסיף רבי עקיבה
שנישאת גש3  Geniza??
שניכנסה גש3  Geniza??
ניבעלה גש3  Geniza??
SV not in body ר' יוסף הכהן ור' זכריה בן הקצב
וריחקוהא גש3  Geniza??
המשפחה גש3  Geniza??
SV not in body המשפחה
ועידיה גש3  Geniza??
ניטמאה גש3  Geniza??
ניסתרה גש3  Geniza??
ניטמאה גש3  Geniza??
ניסתרה גש3 גש4  Geniza??
ניסתרה גש3  Geniza??
ניטמאה גש3  Geniza??
SV not in body כשירה לכהונה
העיסה גש3  Geniza??
זכיי גש3 גש4  Geniza??
זכיי גש3  Geniza??
יוסה גש3 גש4  Geniza??
יוסה גש3  Geniza??
מטבחייה גש4  Geniza??
דכיין גש3  Geniza??
ודי יקרב גש4  Geniza??
SV not in body ודי יקרב
למיתה גש6  Geniza??
יוסה גש3 גש4 גש6  Geniza??
יוסה גש3 גש4  Geniza??
יוסה גש3  Geniza??
שנימצאו גש3  Geniza??
הכל גש3  Geniza??
שיהו גש3  Geniza??
זכיי גש3 גש4  Geniza??
זכיי גש3  Geniza??
וקרבה גש3  Geniza??
בין ג3J גש3  Geniza??
בין ג3J  Geniza??
SV not in body לרחק ולקרב
המחלקות גש3  Geniza??
SV not in body לא לרחק ולא לקרב

In [212]:
second_words= set()
for page in all_pages:
    cola= [p.text for p in page[1][1:]]
    for i in range(len(cola)):
        sv, varts = None, None
        splt = cola[i].split(" |")
        if len(splt) == 1:
            sv = splt[0]
        else:
            sv = splt[0]
            varts = splt[1]
        if "\t" in sv:
            sv= sv.split("\t")[1]
        if "..." in sv:
            sv = sv.split("...")[0].strip()
        if len(sv.split())>1:
            second_words.add(sv.split()[1])
            if "משנה" in sv:
                print(len(sv.split()),sv)
print([w for w in second_words if w[0]=='ג'])

2 משנה ב
2 משנה ג
2 משנה ד
2 משנה ה
2 משנה ו
2 משנה ז
2 משנה ח
2 משנה ט
2 משנה י
2 משנה יא
2 משנה יב
2 משנה יג
2 משנה יד
2 משנה יה
2 משנה יו
2 משנה ב
2 משנה ג
2 משנה ד
2 משנה ה
2 משנה ו
2 משנה ז
2 משנה ח
2 משנה ט
2 משנה י
2 משנה יא
2 משנה ב
2 משנה ג
2 משנה ד'
2 משנה ה
2 משנה ו
2 משנה ז
2 משנה ח
2 משנה ט
2 משנה י
2 משנה יא
2 משנה יב
2 משנה יג
2 משנה יד
2 משנה ד
2 משנה ה
2 משנה ו
2 משנה ט
2 משנה י
2 משנה יא
2 משנה ב
2 משנה ג
2 משנה ד'
2 משנה ה'
2 משנה ז
2 משנה ח
2 משנה ט
2 משנה ג
2 משנה ד
2 משנה ה
2 משנה ו
2 משנה ח
2 משנה ט
2 משנה י
2 משנה יא
2 משנה ב
2 משנה ז
2 משנה ח
2 משנה ט
['גילגילון', 'גוג', "גמליא'", 'גש1', 'גש4', 'גת|', 'גש3', 'גש5', 'ג', 'גA', 'גמליאל', 'גJ1', 'גM', 'ג3J', 'גש6', 'גJ2', 'גת']

In [213]:
from docx import Document
from docx.shared import Inches

def match_sv(page):
    body = [p.text for p in page[0]]
    cola = page[1][1:]  # remove the header
    colb = page[2][1:]  # remove the header
    body_txt = " ".join(body).replace("\t", " ")
    body_txt = ' '.join(body_txt.split())
    body_txt = ''.join([i for i in body_txt if not i.isdigit()])
    
    remaining_body = body_txt
    body_matched = []
    
    for i in range(len(cola)):
        if cola[i].text == '':
            body_matched.append('')
            continue
        
        sv, varts = None, None
        splt = cola[i].text.split("|")
        if len(splt) == 1:
            sv = splt[0].strip()
        else:
            sv = splt[0].strip()
            varts = splt[1].strip()
        if "..." in sv:
            sv = sv.split("...")[0].strip()
        geniza= ['גש1', 'גש4', 'גש3', 'גש5', 'גA', 'גJ1', 'גM', 'ג3J', 'גש6', 'גJ2', 'גת']
        while len(sv.split())>1 and sv.split()[-1] in geniza:
            print(sv," Geniza??")   
            sv = " ".join(sv.split()[:-1]).strip()
        if sv.split()[0].strip()=="משנה" and len(sv.split())==2:
            if sv.split()[1][-1]=="'":
                sv = sv.split()[1]
            else:
                sv = sv.split()[1]+"'"
        if sv and sv[-1].isdigit():
            sv = sv[:-1]        
        if "\t" in sv:
            sv = sv.split("\t")[1]
        if sv not in remaining_body:
            print("SV not in body", sv)
            body_matched.append('?')
        else:
            body_index = remaining_body.index(sv)
            body_matched.append(remaining_body[:body_index + len(sv)])
            remaining_body = remaining_body[body_index + len(sv):]
    
    return body_matched, cola, colb

def create_output_document(pges):
    output_doc = Document()
    
    for page_num, page in enumerate(pges, 1):
        output_doc.add_heading(f'Page {page_num}', level=1)
        
        body_matched, cola, colb = match_sv(page)
        
        # Create table for columns
        table = output_doc.add_table(rows=len(body_matched) + 1, cols=2)
        table.style = 'Table Grid'
        
        # Add headers
        headers = table.rows[0].cells
        headers[0].text = "Body Matched"
        headers[1].text = "Combined Columns"
        
        # Add content
        for i in range(len(body_matched)):
            row = table.rows[i + 1].cells
            row[0].text = body_matched[i]
            
            # Create combined column
            combined_para = row[1].add_paragraph()
            # Copy cola
            for run in cola[i].runs:
                new_run = combined_para.add_run(run.text)
                copy_run_format(new_run, run)
            # Add separator
            combined_para.add_run(" // ")
            # Copy colb if it exists
            if i < len(colb):
                for run in colb[i].runs:
                    new_run = combined_para.add_run(run.text)
                    copy_run_format(new_run, run)
        
        # Add parallels
        if page[3]:
            output_doc.add_paragraph("Parallels:")
            for para in page[3]:
                new_para = output_doc.add_paragraph()
                copy_paragraph_format(new_para, para)
                for run in para.runs:
                    new_run = new_para.add_run(run.text)
                    copy_run_format(new_run, run)
        
        # Add page break
        output_doc.add_page_break()
    
    return output_doc

# Use the functions
input_file = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition.docx'
output_file = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition_output2.docx'

pges = process_document(input_file)
output_doc = create_output_document(pges)
output_doc.save(output_file)

print(f"Processed document saved as {output_file}")

Uneven lines 0 jump 0
4 14 15 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2
SV not in body משנה ג
SV not in body וחכמ'
SV not in body כדבר'
SV not in body אלא
SV not in body ומחצה
SV not in body חייבין
SV not in body בחלה
SV not in body ומשהיגדילו
SV not in body המידות
SV not in body אמרו
SV not in body חמשת
SV not in body רבעים
SV not in body רבעים
SV not in body חייבין
SV not in body חייבין
SV not in body יוסה
SV not in body אומ'
SV not in body חמשה
SV not in body פטורין
SV not in body חמשה
SV not in body חייבין
SV not in body ד'
SV not in body הלל
SV not in body או'
Processed document saved as /Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Sample Eduyot Critical Edition_output2.docx

In [214]:
input_file = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Eduyot Critical Edition.docx'
output_file = '/Users/ephraimmeiri/Downloads/R Wieder mishnah edition processing/Eduyot Critical Edition_output2.docx'

pges = process_document(input_file)
output_doc = create_output_document(pges)
output_doc.save(output_file)

print(f"Processed document saved as {output_file}")

Uneven lines 0 jump 1
4 26 28 4
Uneven lines 1 jump 0
3 29 30 4
Uneven lines 2 jump 0
3 32 33 2
3 33 33 0
3 29 12 0
Uneven lines 5 jump 0
3 25 26 5
4 30 11 0
Uneven lines 7 jump 0
3 29 30 5
Uneven lines 8 jump 1
3 25 27 4
Uneven lines 9 jump 0
3 29 30 4
Uneven lines 10 jump 0
3 33 34 3
Uneven lines 11 jump 2
3 29 32 1
Uneven lines 12 jump 1
3 28 30 1
Uneven lines 13 jump 0
4 31 32 4
Uneven lines 14 jump 1
3 30 32 4
Uneven lines 15 jump 4
3 28 33 1
Uneven lines 16 jump 3
3 26 30 4
Uneven lines 17 jump 0
3 28 29 5
Uneven lines 18 jump 0
3 28 29 1
3 27 28 0
3 38 35 0
3 31 31 0
Uneven lines 22 jump 1
3 31 33 1
Uneven lines 23 jump 0
3 25 26 1
Uneven lines 24 jump 1
5 31 33 3
Uneven lines 25 jump 0
3 27 28 9
Uneven lines 26 jump 2
3 31 34 1
Uneven lines 27 jump 0
3 29 30 4
Uneven lines 28 jump 0
3 26 27 5
Uneven lines 29 jump 1
3 30 32 4
Uneven lines 30 jump 0
3 27 28 4
Uneven lines 31 jump 1
3 29 31 4
Uneven lines 32 jump 0
3 30 31 5
Uneven lines 33 jump 0
3 30 31 4
Uneven lines 34 jump 0
3 28 29 4
3 29 28 0
Uneven lines 36 jump 0
3 28 29 3
3 33 7 0
3 28 3 0
Uneven lines 39 jump 0
5 25 26 5
Uneven lines 40 jump 2
3 28 31 4
Uneven lines 41 jump 0
4 29 30 4
Uneven lines 42 jump 0
3 32 33 1
4 30 29 0
4 23 18 0
Uneven lines 45 jump 2
3 30 33 4
3 28 19 0
3 26 1 0
3 25 18 0
Uneven lines 49 jump 0
3 29 30 2
Uneven lines 50 jump 1
3 27 29 1
Uneven lines 51 jump 0
3 29 30 3
Uneven lines 52 jump 0
3 31 32 3
Uneven lines 53 jump 1
3 30 32 3
Uneven lines 54 jump 0
3 34 35 1
3 27 27 0
Uneven lines 56 jump 0
3 28 29 3
Uneven lines 57 jump 1
3 31 33 3
Uneven lines 58 jump 1
3 29 31 5
Uneven lines 59 jump 0
3 4 5 53
Uneven lines 60 jump 0
3 30 31 4
Uneven lines 61 jump 0
3 29 30 5
Uneven lines 62 jump 0
3 30 31 3
Uneven lines 63 jump 0
2 27 28 3
Uneven lines 64 jump 0
3 31 32 5
3 26 13 0
Uneven lines 66 jump 2
3 28 31 5
Uneven lines 67 jump 0
3 32 33 3
Uneven lines 68 jump 0
3 22 23 14
Uneven lines 69 jump 0
3 31 32 3
Uneven lines 70 jump 0
3 27 28 4
Uneven lines 71 jump 0
3 27 28 5
Uneven lines 72 jump 0
3 26 27 4
Uneven lines 73 jump 0
3 31 32 2
Uneven lines 74 jump 0
3 30 31 6
Uneven lines 75 jump 0
3 28 29 6
Uneven lines 76 jump 1
3 28 30 7
3 28 15 0
Uneven lines 78 jump 0
3 24 25 5
Uneven lines 79 jump 0
3 24 25 6
Uneven lines 80 jump 0
3 31 32 5
Uneven lines 81 jump 1
3 25 27 4
Uneven lines 82 jump 0
3 33 34 2
Uneven lines 83 jump 1
3 30 32 5
Uneven lines 84 jump 1
3 25 27 6
3 30 27 0
3 26 14 0
Uneven lines 87 jump 0
3 24 25 9
Uneven lines 88 jump 3
3 28 32 5
Uneven lines 89 jump 0
3 29 30 5
Uneven lines 90 jump 0
3 27 28 2
3 29 1 0
3 30 1 0
Uneven lines 93 jump 0
5 29 30 4
3 29 21 0
4 30 4 0
3 31 1 0
Uneven lines 97 jump 0
4 27 28 6
3 28 16 0
3 28 1 0
3 31 1 0
3 27 1 0
3 29 1 0
3 30 1 0
3 24 5 0
3 28 1 0
Uneven lines 106 jump 1
3 33 35 3
Uneven lines 107 jump 0
5 29 30 3
Uneven lines 108 jump 2
3 26 29 4
Uneven lines 109 jump 0
3 26 27 7
3 25 18 0
Uneven lines 111 jump 0
3 33 34 1
Uneven lines 112 jump 0
3 33 34 1
3 27 16 0
Uneven lines 114 jump 0
3 25 26 3
Uneven lines 115 jump 0
3 23 24 6
Uneven lines 116 jump 1
4 21 23 11
Uneven lines 117 jump 1
3 27 29 4
Uneven lines 118 jump 0
4 28 29 4
Uneven lines 119 jump 1
3 28 30 5
Uneven lines 120 jump 2
3 31 34 4
Uneven lines 121 jump 0
3 24 25 12
Uneven lines 122 jump 0
3 23 24 8
Uneven lines 123 jump 0
3 28 29 9
Uneven lines 124 jump 0
3 23 24 10
3 25 10 0
Uneven lines 126 jump 0
3 33 34 4
Uneven lines 127 jump 1
3 28 30 7
3 30 5 0
Uneven lines 129 jump 1
3 27 29 4
3 22 2 0
SV not in body משנה ג
SV not in body וחכמ'
SV not in body כדבר'
SV not in body אלא
SV not in body ומחצה
SV not in body חייבין
SV not in body בחלה
SV not in body ומשהיגדילו
SV not in body המידות
SV not in body אמרו
SV not in body חמשת
SV not in body רבעים
SV not in body רבעים
SV not in body חייבין
SV not in body חייבין
SV not in body יוסה
SV not in body אומ'
SV not in body חמשה
SV not in body פטורין
SV not in body חמשה
SV not in body חייבין
SV not in body ד'
SV not in body הלל
SV not in body או'
SV not in body מים
SV not in body שאובין
SV not in body שאדם חייב לומר כלשון רבו
SV not in body שאדם חייב
SV not in body תשעת קבין
SV not in body גדול ממנו
SV not in body בחכמה
SV not in body אבל לא
SV not in body במיניין
SV not in body במינין
SV not in body בחכמה
SV not in body אינו
SV not in body יכול
SV not in body את
SV not in body דברו
SV not in body עד שיהא גדול ממנו בחכמה ובמיניין
SV not in body שיהא
2	ובמיניין גM  Geniza??
SV not in body 2 ובמיניין
SV not in body אמ'
SV not in body המרובין
פל' גM  Geniza??
שמעתה גM  Geniza??
SV not in body שמי
SV not in body ובית
SV not in body הלל
SV not in body העצמות
SV not in body מרוב הביניין או
10	הביניין גM  Geniza??
SV not in body 10 הביניין
SV not in body שורים
SV not in body ושפים
SV not in body בטהרה
SV not in body ומאכילין בטומאה
SV not in body ומאכילין
SV not in body בטומאה
SV not in body ובית הלל
SV not in body ובית
SV not in body הלל
SV not in body או'
SV not in body שורים
SV not in body בטהרה
SV not in body ושפים
SV not in body ומאכילין
SV not in body בטומאה
SV not in body שמי
SV not in body או'
SV not in body שמי
כל גM  Geniza??
שקל גM  Geniza??
ושקל גM  Geniza??
SV not in body יא'
SV not in body מעשר
SV not in body שמי
SV not in body ובית
SV not in body הלל
SV not in body ובדינר
SV not in body ור' עקיבה
SV not in body עקיבה
SV not in body בשלשה
SV not in body דינרין
SV not in body ובריבעית כסף
SV not in body ובריבעית
SV not in body כסף וברביעית מעות
SV not in body וברביעית
SV not in body מעות
SV not in body ור'
SV not in body טרפון
SV not in body או'
SV not in body משנה יב
SV not in body ובית הלל
SV not in body מטהרין
SV not in body שמי
SV not in body אומ'
SV not in body מלבין
שלכסא גM  Geniza??
SV not in body שלכסא
SV not in body טמא
SV not in body כסא
SV not in body שקבעו
SV not in body בעריבה
SV not in body בית שמי
SV not in body שמי
SV not in body מטמין
SV not in body העשוי בה
SV not in body משנה יג
SV not in body להודות
SV not in body כדברי
SV not in body בית שמי
SV not in body שמי
SV not in body האשה
SV not in body שבאת
SV not in body ממדינת
SV not in body ואמרה
SV not in body בעלי
8	תינשא גM  Geniza??
SV not in body 8 תינשא
SV not in body בעלי
SV not in body תיתיבם
SV not in body תיתיבם
SV not in body ובית הלל
SV not in body אמרו
SV not in body להן
SV not in body בית שמי
SV not in body שמי
SV not in body הקציר
הזיתין גM  Geniza??
SV not in body הזיתין
SV not in body ואחת
SV not in body ואחת
SV not in body הבאה
SV not in body ממדינת
דיברו גת  Geniza??
SV not in body יד'
SV not in body בית שמי
SV not in body שמי
תינשא ותיטול גת  Geniza??
SV not in body תינשא
SV not in body בית שמי
SV not in body שמי
היתרתם גת  Geniza??
SV not in body החמורה
SV not in body הלל
SV not in body בית שמי
SV not in body שהוא
SV not in body כותב
SV not in body שאם תנשא
SV not in body תנשא
תיטלי גת  Geniza??
SV not in body תיטלי
SV not in body שכתוב
SV not in body ליך
SV not in body חזרו
SV not in body בית הלל
SV not in body הלל
SV not in body להדות
SV not in body שמי
SV not in body יה'
SV not in body אחד
SV not in body אחד
SV not in body כדברי בית הלל
SV not in body כדברי
SV not in body בית הלל
SV not in body הלל
SV not in body בית שמי אומ'
SV not in body בית שמי
SV not in body שמי
SV not in body אומ'
תיקנתם גת  Geniza??
SV not in body ואת
SV not in body עצמו
תיקנתם גת  Geniza??
SV not in body תיקנתם
SV not in body אינו יכול
SV not in body בת
SV not in body חורים
SV not in body אינו יכול
SV not in body אינו
SV not in body יכול
SV not in body יבטל
SV not in body והלא
SV not in body ניברא
SV not in body אלא
SV not in body לפירייה
SV not in body וריבייה
SV not in body שנ'
SV not in body שנ'
SV not in body תוהו
SV not in body בראה
SV not in body לשבת
SV not in body יצרה
SV not in body אלא
SV not in body מפני תיקון העולם
SV not in body תיקון
SV not in body העולם
SV not in body להודות
SV not in body כדברי
SV not in body בית
SV not in body שמי
SV not in body יו'
חרס גת  Geniza??
SV not in body חרס
SV not in body על
SV not in body כדברי
SV not in body בית הלל
SV not in body הלל
SV not in body בית
SV not in body בית שמי
SV not in body שמי
SV not in body חרס
SV not in body מפני מה
SV not in body אמרו
SV not in body להן
SV not in body בית שמי
SV not in body שמי
SV not in body שהוא
SV not in body טמא
SV not in body גב עם
SV not in body הארץ
SV not in body טמא
SV not in body חוצץ
SV not in body אמרו להן
SV not in body אמרו
SV not in body להן
SV not in body בית הלל
SV not in body אמרו
SV not in body להן
SV not in body שמי
SV not in body אכלים ומשקים שבתוכו
SV not in body בית הלל
SV not in body שמי
SV not in body משנה ב
SV not in body עקיבה
27	שניטמא גת  Geniza??
SV not in body 27 שניטמא
SV not in body אמ'
SV not in body אמ'
SV not in body ר'
טריפה גת  Geniza??
הן גת  Geniza??
ירוש' גת  Geniza??
SV not in body בו
SV not in body אחד
SV not in body והיה מלווה
מלווה גת  Geniza??
SV not in body לפי דרכך אתה למד
SV not in body אמ'
SV not in body ר'
18	שלתרומה גת  Geniza??
SV not in body 18 שלתרומה
SV not in body של בעל
SV not in body לאו
SV not in body הרי
26	תיזרע גת  Geniza??
SV not in body 26 תיזרע
SV not in body יהושע
SV not in body ר' אלעזר
SV not in body הזב
SV not in body טהורות
SV not in body אמ'
SV not in body ישמעא'
SV not in body הודה
SV not in body והבושר
SV not in body והמלילות
SV not in body מבעוד
SV not in body יום
SV not in body משנה ח
SV not in body משם
SV not in body ואחד
SV not in body משם
SV not in body שנים
SV not in body משם
SV not in body אליעזר
SV not in body יוצא
SV not in body העדות
SV not in body אמ'
SV not in body סנדל
SV not in body ארבע מאות
SV not in body שנה
SV not in body יא'
SV not in body שלשנים עשר
SV not in body שנים עשר
SV not in body משפט
SV not in body רשעים
12	המיטמים גJ2  Geniza??
SV not in body 12 המיטמים
SV not in body ומאהיל
SV not in body או נוגע בכחצי זית
SV not in body כשני חצאי
SV not in body כשני
SV not in body חצאי
SV not in body זיתים
SV not in body ומאהיל
SV not in body עד
SV not in body זיית
SV not in body וחצי
SV not in body זית
SV not in body מאהיל
23	הנוגיע גJ2  Geniza??
SV not in body 23 הנוגיע
24	על גJ2  Geniza??
SV not in body 24 על
SV not in body ודבר אחר
SV not in body מאהיל
SV not in body עליו
26	על גJ2  Geniza??
SV not in body 26 על
SV not in body זית
SV not in body אמ'
SV not in body מאיר
SV not in body מצטרף
SV not in body דוסא
SV not in body וחכ' אומ' מצטרף מחללין מעשר שני על אסימון דברי ר' דוסא (שורה 4)
SV not in body אוסרין
SV not in body מטבילין
ידיים גJ2  Geniza??
SV not in body ידיים
SV not in body לחטאת
SV not in body דב'
SV not in body דוסא
SV not in body וחכמ'
ניטמא גJ2  Geniza??
SV not in body דבר'
SV not in body דוסא
SV not in body קיבול
SV not in body אריג
SV not in body טמאה
SV not in body ושלעור
SV not in body ר'
SV not in body ארכינס
SV not in body מטהר
SV not in body וחכמ'
SV not in body מטמים
SV not in body ניפסק
SV not in body אצבע
SV not in body שלה
SV not in body טהורה
SV not in body ובית

IndexError: list index out of range